### ISSUE TITLE
Icon width is shrinking

### ISSUE THREAD

**Issue by plsdev89** [carmelopullara/react-feather#111]
When using icon inside div, its width is shrinking.
This is the sandbox to reproduce the issue.
https://codesandbox.io/s/feather-icon-wrong-width-rn25rn?file=/src/App.js

As you can see from below screenshot, its width is 24.52.
But I suppose that it should be 50 as I set size as 50.

To fix this problem, I have to set minWidth: 50 like this : `<MoreHorizontal size="50" style={{ minWidth: 50 }} />`.
But I think that it's not good solution.
Is there a better way to handle this? or Can it be resolved on react-feather library itself.

![image](https://github.com/feathericons/react-feather/assets/95106623/5fb20209-5597-480d-8d59-41eee926d850)

**Comment by imMatheus** [comment]
Your link does not work unfortunately, but I would get this is a flex box issue tbh and not related to the feather icons. To fix this add `flex-shrink: 0` to you icon (this is a pretty common thing that happens in flexbox with elements that don't have any "real" content inside AKA text)

**Comment by plsdev89** [comment]
@imMatheus Thanks for your comment, I was wondering if react-feather library can handle it automatically.
Anyway, I am closing the issue since it's not critical.
