### ISSUE TITLE
Change Icon Color onHover

### ISSUE THREAD

**Issue by Blackjack92** [carmelopullara/react-feather#24]
Hello,

is there any easy way to add a hover effect e.g. when mouseOver change color to yellow?
I tried the following:

```
onMouseOver={(evt) => evt.target.setAttribute('style', 'stroke: gray')}
onMouseLeave={(evt) => evt.target.setAttribute('style', 'stroke: white')}
```

But this has got a problem with multiple paths. It does only color the selected path not all paths of the svg.

**Comment by carmelopullara** [comment]
You can easily achieve that with CSS.

https://css-tricks.com/using-svg/#article-header-id-9
