### ISSUE TITLE
Zap Icon is filled with dark color and fill="none" is not helpful to get rid of it

### ISSUE THREAD

**Issue by vizFlux** [carmelopullara/react-feather#3]
```JavaScript
<Zap fill="none" stroke="#4A76F8" />
```

<img width="43" alt="screen shot 2017-08-18 at 12 55 08 pm" src="https://user-images.githubusercontent.com/13939164/29444729-8ffa4e3c-8414-11e7-8bbb-120878324e86.png">

**Comment by carmelopullara** [comment]
I've just tried to replicate the issue and the icon is not filled. Are you sure it's not filled with CSS?

Anyway, you don't need to pass "fill" and "stroke" as props. You should pass only "color" and "size" props. The "fill" attribute is already set to none, for all icons.
