### ISSUE TITLE
When using non-ES6 imports, need to specify the exported default

### ISSUE THREAD

**Issue by kurttheviking** [carmelopullara/react-feather#5]
From what I can tell, the [README suggests the following approach to import the `Camera`](https://github.com/carmelopullara/react-feather/blob/5af9eadecfdba36d79ce9ad0f55b668cb9820963/README.md#usage) component in the absence of ES6 imports:

```js
var Camera = require('react-feather/dist/icons/camera');
```

However, the published `dist/.../camera.js` file exports like this:

```js
exports.default = Camera;
```

Thus, it seems like the README should read:

> If you can't use ES6 imports, it's possible to include icons from the compiled folder ./dist.

```js
var Camera = require('react-feather/dist/icons/camera').default;

var MyComponent = React.createClass({
  render: function () {
    return (
      <Camera />
    );
  }
});
```

Or, perhaps, I am just missing something...

**Comment by carmelopullara** [comment]
Yes, you are completely right. I'm going to update the README.

Thanks!
